### ISSUE TITLE
Popovers with Apostrophe w/in Chunk not Working

### ISSUE THREAD

**Issue by whamrick** [leamh/leamh-wp-theme#102]
For example, the chunk "d’fhios Eamhna na mbánshroth mbinn" in the Text "Cú Chulainn an Chroidhe Mhir" (Quatrain 29).

http://leamh.org/texts/cu-chulainn-an-chroidhe-mhir/

**Comment by whamrick** [comment]
Within "Cú Chulainn an Chroidhe Mhir" I can get all of the chunks to work except:

"Bheith dom chroidhe d’fheoil nó d’fhuil" (quatrain 37).

I've triple-checked the JSON file, cleared formatting and even re-written the chunk altogether -s till no luck.  The only thing different I notice here is that there are two apostrophes in the chunk.

Also, in "Brian Ó Ruairc," all chunks work except:

"ó Raith Té".

I believe this is the only chunk thus far that starts with a vowel having an accent mark (or "fada"). Not sure if that's an issue.

**Comment by joelsalisbury** [comment]
So I've narrowed this down to an issue distinguishing between a single
quote and an apostrophe. It appears the data and the content at often out
if sync in that regard. Additionally there appears to sometimes be some
funky backwards apostrophe thing. Acutes and fadas and the like do not
appear to have an impact. We are trying to write some code to sanitize the
data.

On Sep 20, 2017 2:24 PM, "whamrick" <notifications@github.com> wrote:

Within "Cú Chulainn an Chroidhe Mhir" I can get all of the chunks to work
except:

"Bheith dom chroidhe d’fheoil nó d’fhuil" (quatrain 37).

I've triple-checked the JSON file, cleared formatting and even re-written
the chunk altogether -s till no luck. The only thing different I notice
here is that there are two apostrophes in the chunk.

Also, in "Brian Ó Ruairc," all chunks work except:

"ó Raith Té".

I believe this is the only chunk thus far that starts with a vowel having
an accent mark (or "fada"). Not sure if that's an issue.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/leamh/leamh-wp-theme/issues/102#issuecomment-330938780>,
or mute the thread

**Comment by joelsalisbury** [comment]
"Straight quotes" vs "Curly Quotes," that is.

**Comment by whamrick** [comment]
> It appears the data and the content at often out
if sync in that regard. Additionally there appears to sometimes be some
funky backwards apostrophe thing.

I had noticed that, too.

**Comment by joelsalisbury** [comment]
@whamrick , Give the "apostrophe offenders" another try. I believe I have fixed it now.

In regards to the chunk "ó Raith Té", it's not actually in the JSON file as a chunk. See here: http://leamh.org/wp-content/uploads/2016/03/Brian_O_Ruairc_Sept_13-1.txt

I found a few others that might not work ( d’aonrún ), but that's because the words themselves are not in the JSON data. Rather, in that specific example, "d'" is in the data.

For still others, such as ("‘na rígh Uladh")  unless there is a syntactical reason to use the upside-downy apostrophe (clearly, I am a linguist), it needs to be input in the JSON with a single quote. Let me know on that!

**Comment by joelsalisbury** [comment]
And on another note, if the curly-quotes, upside-downy apostrophes, and straight-quotes have no syntactical difference (and are thus just a result of copy-paste things), we can sanitize the data both ways and standardize on something the code can use. That'll mean that the JSON process can be slightly less laborious.

**Comment by whamrick** [comment]
@joelsalisbury 

OK, so "ó Ráith Té" was in the JSON, but with the accent on the "a":

{
"id":"Ã³ RÃ¡ith TÃ©",
"translation":"'from RÃ¡ith TÃ©'",
"notes":"tells where Brian Ã“ Ruairc is from"
},

 I re-uploaded the JSON file without the accent mark and now it works fine.  This was just a mundane text-JSON mismatch.  Whew!  

Checking the other offenders now...

**Comment by whamrick** [comment]
@joelsalisbury 
I fixed those single quotes in the Marbhadh text that you noticed and they work now.  So does "d'aonrún" from the other text.

So...it looks like this was, in fact, just a copy-paste issue from Word to JSON.

Going forward, then, we just need to be sure to use regular, old single quotation marks, not the fancy apostrophe that Word cooks up -- is that it?  If so, let's close this one.

Thanks, Joel!

**Comment by joelsalisbury** [comment]
That's indeed the case! Additionally, I will put some safeguards into the
code which could help prevent the issue.

On Sep 20, 2017 5:14 PM, "whamrick" <notifications@github.com> wrote:

@joelsalisbury <https://github.com/joelsalisbury>
I fixed those single quotes in the Marbhadh text that you noticed and they
work now. So does "d'aonrún" from the other text.

So...it looks like this was, in fact, just a copy-paste issue from Word to
JSON.

Going forward, then, we just need to be sure to use regular, old single
quotation marks, not the fancy apostrophe that Word cooks up -- is that it?
If so, let's close this one.

Thanks, Joel!

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/leamh/leamh-wp-theme/issues/102#issuecomment-330983008>,
or mute the thread
